name: CI

on:
  push:
    branches:
      - main
      - 'milestone/**'
  pull_request:
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cc'
      - '**.cpp'
      - '**.yml'
  workflow_dispatch:

jobs:
  ci:
    runs-on: [ubuntu-22.04]
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 'prepare for build - install python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'prepare for build - install meson and ninja'
        run: pip install meson ninja

      - name: 'prepare for build - install g++-13'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13

      - name: 'prepare for build - install tbb'
        run: sudo apt install libtbb-dev

      - name: 'compile'
        run: meson setup build

      - name: 'run all tests'
        run: meson test -C build/ -v

      - name: 'upload test log if test failed'
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: meson_test_log
          path: build/meson-logs/testlog.txt

